theme = "dracula-tami"

[editor]
mouse = true
idle-timeout = 0
true-color = true
line-number = "relative"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.normal."+"]
b = ":sh npm run build"