theme = "new-tami"

[editor]
mouse = true
idle-timeout = 0
true-color = true
line-number = "relative"
cursorline = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.normal."+"]
b = ":sh buildt"
r = ":sh runt"
