[[language]]
name = "javascript"
auto-format = true

[[lanugage]]
name = "c-sharp"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt"}
auto-format = true

[[language]]
name = "glsl"
language-servers = [ "glsl_analyzer" ]
auto-format = true

[language-server.glsl_analyzer]
command = "glsl_analyzer"

[language-server.omnisharp]
command = "OmniSharp"
args = [ "--languageserver"]
config = { useModernNet = false }
timeout = 300
