#!/usr/bin/env bash
# A rebuild script that commits on a successful build
set -e

CONFIG_PATH="/home/tamara/nix-system"

# cd to your config dir
# pushd /etc/nixos
pushd $CONFIG_PATH

git restore nixos-deploy.log
git restore nixos-switch.log
git pull
nix flake lock --update-input custom-pkgs

# Edit your config
$EDITOR flake.nix

# Autoformat your nix files
# alejandra . &>/dev/null

# Shows your changes
find . -name "*.nix" | xargs -I {} git diff -U0 {}

echo 
echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
# sudo nixos-rebuild switch --flake $CONFIG_PATH/ &> nixos-switch.log || (cat nixos-switch.log | grep --color error && false)
sudo nixos-rebuild switch --flake $CONFIG_PATH/ 2>&1 | tee nixos-switch.log
exit_code=${PIPESTATUS[0]}
if [ $exit_code -ne 0 ]; then
    grep --color error nixos-switch.log
    exit $exit_code
fi

# Get current generation metadata
current="$(hostname) - $(nixos-rebuild list-generations | grep current | sed 's/ *[*]*$//' | sed 's/current/generation/' | sed 's/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}//')"

echo
echo "Git shenanigans: "
# Commit all changes with the generation metadata
git commit -am "$current"
git push
# Back to where you were
popd

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
